=== bergsteiger/realwork/quality/test/armadillo/ra/TestUsersAndGroups/metadata.dtd
<!ELEMENT Metadata (ObjectType+)>
<!ATTLIST Metadata Version CDATA #REQUIRED>
<!ELEMENT ObjectType (ObjectDescription?, ObjectFlags, MessageIndex,
          FolderName?, ObjectNameProperty?, 
          PropertyType+, RelationshipType*, ExportAs?)>
<!ATTLIST ObjectType TypeID CDATA #REQUIRED>
<!ELEMENT ExportAs (#PCDATA)>
<!ELEMENT MessageIndex (#PCDATA)>
<!ELEMENT ObjectDescription (#PCDATA)>
<!ELEMENT ObjectFlags (#PCDATA)>
<!ELEMENT FolderName (#PCDATA)>
<!ELEMENT ObjectNameProperty (#PCDATA)>
<!ELEMENT PropertyType (PropertyDescription?,   PropertyCardinality?, DirectoryName?, FileExtension?,
 PropertyFlags, MessageIndex, ListID?, MaxLength?,  DataType, ValueType,
  DefaultValue?, VisibleName?, ExportAs?)>
<!ATTLIST PropertyType TypeID CDATA #REQUIRED>
<!ELEMENT PropertyDescription (#PCDATA)>
<!ELEMENT FileExtension (#PCDATA)>
<!ELEMENT DirectoryName (#PCDATA)>
<!ELEMENT PropertyFlags (#PCDATA)>
<!ELEMENT ListID (#PCDATA)>
<!ELEMENT MaxLength (#PCDATA)>
<!ELEMENT DataType (#PCDATA)>
<!ELEMENT ValueType (#PCDATA)>
<!ELEMENT DefaultValue (#PCDATA)>
<!ELEMENT PropertyCardinality (#PCDATA)>
<!ELEMENT VisibleName (#PCDATA)>
<!ELEMENT RelationshipType (RelationshipDescription?, RelationshipCardinality,
 MessageIndex, TargetTypeID, RelationshipFlags, ExportAs?)>
<!ATTLIST RelationshipType TypeID CDATA #REQUIRED>
<!ELEMENT RelationshipDescription (#PCDATA)>
<!ELEMENT RelationshipCardinality (#PCDATA)>
<!ELEMENT TargetTypeID (#PCDATA)>
<!ELEMENT RelationshipFlags (#PCDATA)>

=== bergsteiger/realwork/quality/test/armadillo/ra/TestDatastore/DefaultTestScriptDatastore/tssmetadata.xml
<?xml version="1.0"?>
<!DOCTYPE Metadata SYSTEM "metadata.dtd">
<Metadata Version="1.0">
	<ObjectType TypeID="RootFolder">
		<ObjectDescription>System: Root Folder</ObjectDescription>
		<ObjectFlags>6</ObjectFlags>
		<FolderName>Root</FolderName>
		<PropertyType TypeID="UID">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>2</MessageIndex>
			<Flags>0</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Name">
			<PropertyCardinality>1</PropertyCardinality>
			<Flags>0</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
	</ObjectType>
	<ObjectType TypeID="ListType">
		<ObjectDescription>System: List Definition</ObjectDescription>
		<ObjectFlags>4</ObjectFlags>
		<FolderName>TMS_ListTypes</FolderName>
		<PropertyType TypeID="ListData">
			<PropertyCardinality>2</PropertyCardinality>
			<Flags>0</Flags>
			<MaxLength>30</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<RelationshipType TypeID="Parent">
			<RelationshipCardinality>1</RelationshipCardinality>
			<TargetTypeID>TMS_TATCustomizations</TargetTypeID>
		</RelationshipType>
	</ObjectType>
	<ObjectType TypeID="TATCustomization">
		<ObjectDescription></ObjectDescription>
		<ObjectFlags>4</ObjectFlags>
		<FolderName>TMS_TATCustomizations</FolderName>
		<PropertyType TypeID="PropertyNames">
			<PropertyCardinality>2</PropertyCardinality>
			<Flags>0</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>8</ValueType>
		</PropertyType>
		<RelationshipType TypeID="Parent">
			<RelationshipCardinality>1</RelationshipCardinality>
		      	<TargetTypeID>TMS_TATCustomizations</TargetTypeID>
		</RelationshipType>
	</ObjectType>
	<ObjectType TypeID="Script">
		<ObjectDescription>Script</ObjectDescription>
		<ObjectFlags>405</ObjectFlags>
		<MessageIndex>12</MessageIndex>
		<FolderName>TMS_Scripts</FolderName>
		<PropertyType TypeID="UID">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>2</MessageIndex>
			<Flags>1</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Name">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>1</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Description">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>7</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="CreationDate">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>3</MessageIndex>
			<Flags>57</Flags>
			<DataType>4</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="ModificationDate">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>4</MessageIndex>
			<Flags>57</Flags>
			<DataType>4</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="LastModifiedBy">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>6</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>50</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="CreatedBy">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>5</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>50</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Owner">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>8</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Purpose">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>77</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ListID>ScriptPurpose</ListID>
			<ValueType>2</ValueType>
		</PropertyType>
		<PropertyType TypeID="Environment">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>117</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ListID>ScriptEnvironment</ListID>
			<ValueType>2</ValueType>
		</PropertyType>
		<PropertyType TypeID="Type">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>1</Flags>
			<MaxLength>0</MaxLength>
			<DataType>2</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="TypeName">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>64</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Custom1">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>25</MessageIndex>
			<Flags>185</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ListID>ScriptCustom1</ListID>
			<ValueType>2</ValueType>
		</PropertyType>
		<PropertyType TypeID="Custom2">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>26</MessageIndex>
			<Flags>185</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ListID>ScriptCustom2</ListID>
			<ValueType>2</ValueType>
		</PropertyType>
		<PropertyType TypeID="Custom3">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>27</MessageIndex>
			<Flags>185</Flags>
			<MaxLength>40</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Developed">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>42</MessageIndex>
			<Flags>2105</Flags>
			<MaxLength>40</MaxLength>
			<DataType>2</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="SpecFilePath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>43</MessageIndex>
			<Flags>57</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="SpecNotes">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>44</MessageIndex>
			<Flags>32</Flags>
			<MaxLength>0</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Defines">
			<PropertyCardinality>2</PropertyCardinality>
			<MessageIndex>94</MessageIndex>
			<Flags>0</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="Libraries">
			<PropertyCardinality>2</PropertyCardinality>
			<MessageIndex>93</MessageIndex>
			<ExportAs>Library</ExportAs>
			<Flags>0</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="ClassPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>0</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<ValueType>1</ValueType>
		</PropertyType>
		<PropertyType TypeID="VPPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>87</MessageIndex>
			<Flags>16640</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>vp</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="DLLPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>dll</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="IncludePath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>113</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>include</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="LLSPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>112</MessageIndex>
			<Flags>16640</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>lls</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="ExternCPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>externC</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="IDLPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>idl</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="DATPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>0</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>dat</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="SQABasicPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>SQABas32</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="JavaProxiesPath">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>4</Flags>
			<MaxLength>255</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>JavaProxies</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
		<PropertyType TypeID="Win32Path">
			<PropertyCardinality>1</PropertyCardinality>
			<MessageIndex>0</MessageIndex>
			<Flags>16388</Flags>
			<MaxLength>0</MaxLength>
			<DataType>1</DataType>
			<DirectoryName>win32</DirectoryName>
			<ValueType>9</ValueType>
		</PropertyType>
